"""System-wide constants for the Zentex foundation layer."""

TURN_MAX_DURATION_SECONDS: int = 120
NINE_QUESTIONS_MAX_CONCURRENCY: int = 3
SESSION_DEFAULT_TIMEOUT_SECONDS: int = 1800
AUDIT_RETENTION_DAYS: int = 90
SENSORY_SIGNAL_QUEUE_MAX_SIZE: int = 1000
WORKING_MEMORY_MAX_SLOTS: int = 16
PHASE_COUNT: int = 9
NINE_QUESTION_COUNT: int = 9
MAX_TRANSCRIPT_ENTRIES_PER_SESSION: int = 10000
DEFAULT_LLM_TIMEOUT_SECONDS: int = 60
PLUGIN_HEALTH_CHECK_INTERVAL_SECONDS: int = 30
