from __future__ import annotations

import argparse
import inspect
import json
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from fastapi.routing import APIRoute, APIWebSocketRoute  # noqa: E402

from zentex.web_console.app import create_app  # noqa: E402


DOC_PATH = ROOT / "docs" / "API_REFERENCE.md"
OPENAPI_PATH = ROOT / "docs" / "openapi.json"


def _format_annotation(value: Any) -> str:
    if value is None:
        return "-"
    if isinstance(value, str):
        return value
    name = getattr(value, "__name__", None)
    if name:
        return name
    return str(value).replace("typing.", "")


def _escape_cell(value: Any) -> str:
    text = str(value if value is not None else "-")
    return text.replace("|", "\\|").replace("\n", " ").strip() or "-"


def _first_sentence(doc: str | None) -> str:
    if not doc:
        return "-"
    line = " ".join(doc.strip().split())
    return line.split(". ")[0].strip()


def _route_group(path: str, tags: list[str] | None, module: str) -> str:
    if tags:
        useful_tags = [tag for tag in tags if tag != "web-console"]
        if useful_tags:
            return useful_tags[0]
    if path == "/health":
        return "health"
    prefix = "/api/web/"
    if path.startswith(prefix):
        return path[len(prefix) :].split("/", 1)[0]
    parts = path.strip("/").split("/")
    if parts and parts[0]:
        return parts[0]
    return module.rsplit(".", 1)[-1]


def _route_summary(route: APIRoute) -> str:
    return route.summary or _first_sentence(inspect.getdoc(route.endpoint))


def _param_names(route: APIRoute, attr: str) -> str:
    values = getattr(route.dependant, attr, [])
    names = [getattr(param, "name", "") for param in values]
    return ", ".join(name for name in names if name) or "-"


def _body_type(route: APIRoute) -> str:
    body_field = getattr(route, "body_field", None)
    if body_field is None:
        return "-"
    field_info = getattr(body_field, "field_info", None)
    annotation = getattr(field_info, "annotation", None)
    return _format_annotation(annotation or getattr(body_field, "type_", None))


def _response_type(route: APIRoute) -> str:
    return _format_annotation(getattr(route, "response_model", None))


def iter_routes() -> list[dict[str, str]]:
    app = create_app(managed_plugin_records={}, plugin_feature_catalog=[])
    rows: list[dict[str, str]] = []
    for route in app.routes:
        if isinstance(route, APIRoute):
            methods = ", ".join(sorted(route.methods or []))
            tags = list(getattr(route, "tags", []) or [])
            rows.append(
                {
                    "group": _route_group(route.path, tags, route.endpoint.__module__),
                    "method": methods,
                    "path": route.path,
                    "name": route.name,
                    "summary": _route_summary(route),
                    "path_params": _param_names(route, "path_params"),
                    "query_params": _param_names(route, "query_params"),
                    "body": _body_type(route),
                    "response": _response_type(route),
                    "module": route.endpoint.__module__,
                }
            )
        elif isinstance(route, APIWebSocketRoute):
            module = route.endpoint.__module__
            rows.append(
                {
                    "group": _route_group(route.path, None, module),
                    "method": "WS",
                    "path": route.path,
                    "name": route.name,
                    "summary": _first_sentence(inspect.getdoc(route.endpoint)),
                    "path_params": "-",
                    "query_params": "-",
                    "body": "-",
                    "response": "-",
                    "module": module,
                }
            )
    return sorted(rows, key=lambda row: (row["group"], row["path"], row["method"]))


def write_markdown(rows: list[dict[str, str]], output_path: Path) -> None:
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        grouped[row["group"]].append(row)

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    lines = [
        "# API Reference",
        "",
        "> This file is generated by `scripts/generate_api_docs.py` from the FastAPI route table.",
        f"> Generated at: {generated_at}",
        "",
        "## Overview",
        "",
        f"- Total endpoints: `{len(rows)}`",
        "- Main application factory: `zentex.web_console.app:create_app`",
        "- Main API prefix: `/api/web`",
        "- Built-in interactive docs when OpenAPI generation is healthy: `/docs`, `/redoc`, `/openapi.json`",
        "",
        "## Regenerate",
        "",
        "```bash",
        "PYTHONPATH=src .venv/bin/python scripts/generate_api_docs.py",
        "```",
        "",
        "To also try exporting the FastAPI OpenAPI schema:",
        "",
        "```bash",
        "PYTHONPATH=src .venv/bin/python scripts/generate_api_docs.py --openapi",
        "```",
        "",
        "Note: if OpenAPI export fails with a Pydantic `class-not-fully-defined` error, rebuild or fix the referenced Pydantic model before relying on `/docs` or `/openapi.json`.",
        "",
        "## Endpoint Groups",
        "",
    ]

    for group in sorted(grouped):
        methods = sorted({row["method"] for row in grouped[group]})
        lines.append(f"- `{group}`: {len(grouped[group])} endpoint(s), methods: {', '.join(methods)}")
    lines.append("")

    for group in sorted(grouped):
        lines.extend(
            [
                f"## {group}",
                "",
                "| Method | Path | Handler | Summary | Path Params | Query Params | Body | Response | Module |",
                "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
            ]
        )
        for row in grouped[group]:
            lines.append(
                "| "
                + " | ".join(
                    _escape_cell(row[key])
                    for key in (
                        "method",
                        "path",
                        "name",
                        "summary",
                        "path_params",
                        "query_params",
                        "body",
                        "response",
                        "module",
                    )
                )
                + " |"
            )
        lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def write_openapi(output_path: Path) -> None:
    app = create_app(managed_plugin_records={}, plugin_feature_catalog=[])
    schema = app.openapi()
    output_path.write_text(
        json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate API reference docs from FastAPI routes.")
    parser.add_argument("--output", type=Path, default=DOC_PATH, help="Markdown output path.")
    parser.add_argument("--openapi", action="store_true", help="Also export docs/openapi.json.")
    parser.add_argument("--openapi-output", type=Path, default=OPENAPI_PATH, help="OpenAPI JSON output path.")
    args = parser.parse_args()

    rows = iter_routes()
    write_markdown(rows, args.output)
    print(f"Wrote {len(rows)} endpoints to {args.output}")

    if args.openapi:
        write_openapi(args.openapi_output)
        print(f"Wrote OpenAPI schema to {args.openapi_output}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
